### ISSUE TITLE
Security at rest

### ISSUE THREAD

**Issue by winwisely99** [prologic/bitraft#15]
I noticed badger V2 supports encryption at rest.

Is there the possibility of this being added by yourself or me ?

Thankyou for this project.

**Comment by winwisely99** [comment]
I just realised I make an oopsy in assuming this used badgerdb.

Will close

**Comment by prologic** [comment]
Yeah it does not, It in fact uses [Bitcask](https://github.com/prologic/bitcask) -- However I have to ask, is your question still relevant (_possibly it is_)...

**Comment by winwisely99** [comment]
It's ok if it uses it ask for storage.

For our project the main thing we need is pub sub support that matches the Redis API.

Also has this been benchmarked ?
Wondering if it saturates the cpu threads ?

**Comment by winwisely99** [comment]
Reopening :)

**Comment by prologic** [comment]
Yes this has been benchmarked; but it will have to be done again and published.

Can you explain more about what you need a pub/sub API  for? I've never understood why Redis has pub/sub :) Its a key/value store :)

**Comment by winwisely99** [comment]
I saw the benchmarks.

I have to admit that digraph with badgerdb and it's distributed HA is compelling.

Badgerdb just formalised it's encryption at rest. See latest blog post from them.

**Comment by prologic** [comment]
Then by all means use that :)
