### ISSUE TITLE
Allow setting max value size

### ISSUE THREAD

**Issue by iMartyn** [prologic/bitraft#29]
As mentioned in the other issue, I'm using bitraft to store the contents of a struct.  Unfortunately, that struct is pretty big, and so when marshalled to json, it exceeds the size.

As this is a bitcask setting, right now, from what I can tell, this defaults to the bitcask default of 65k, which unfortunately is not enough for my purposes :(

It'd be nice to expose this as a flag.

**Comment by prologic** [comment]
Please do so! PR welcome! I wish I had time to make this Bitraft project into a proper nice distributed form of Bitcask, but I have to rely on you guys to help make this happen! Right now in many of my projects (_and I suspect users of_) are content to use Bitcask in single-process / embedded mode.

**Comment by lalawue** [comment]
'go build' latest source, and place config.json in data directory works fine, config.json like

```json
{"max_datafile_size":1048576,"max_key_size":1024,"max_value_size":67108864,"sync":false,"autorecovery":false}
```

**Comment by prologic** [comment]
Wait. Is this still an issue?
