### ISSUE TITLE
KEYS command in redis-cli returning a syntax error when interacting with bitraft

### ISSUE THREAD

**Issue by regel** [prologic/bitraft#39]
Environment: Running the latest docker image, and redis-cli (on MacOS)

I pulled the docker image and tried to run the 'KEYS' command with an exact match or pattern, but I get an error each time. Error history:

$ redis-cli -p 4920
127.0.0.1:4920> SET xxx 23fesshtrh3
OK
127.0.0.1:4920> GET xx
(nil)
127.0.0.1:4920> GET xxx
"23fesshtrh3"
127.0.0.1:4920> 

127.0.0.1:4920> KEYS 23fesshtrh3
(error) syntax error
127.0.0.1:4920> KEYS "23fesshtrh3"
(error) syntax error
127.0.0.1:4920> KEYS [23fesshtrh3]
(error) syntax error
127.0.0.1:4920> KEYS 23
(error) syntax error
127.0.0.1:4920> KEYS 23*
(error) syntax error
127.0.0.1:4920> KEYS *
(error) syntax error
127.0.0.1:4920> KEYS a??
(error) syntax error
127.0.0.1:4920>

**Comment by prologic** [comment]
Hmm. Possibly a bug in that command handler.

Can you put up a PR to fix this?

**Comment by regel** [comment]
> Hmm. Possibly a bug in that command handler.
> 
> Can you put up a PR to fix this?

Sure I can

**Comment by regel** [comment]
With a 'vanilla' redis running (docker run -p 6379:6379 redis):

$ redis-cli
127.0.0.1:6379> SET xxx abcd
OK
127.0.0.1:6379> keys abcs
(empty array)
127.0.0.1:6379> keys withvalues
(empty array)
127.0.0.1:6379> keys
(error) ERR wrong number of arguments for 'keys' command
127.0.0.1:6379> keys x
(empty array)
127.0.0.1:6379> keys x*
1) "xxx"


Ideally, I'd want bitraft to be a drop-in replacement of redis and therefore implement the very same protocol and functional behavior for the 'KEYS' command. I can put up a PR for this if that's OK ?

**Comment by prologic** [comment]
Yes Please !

**Comment by prologic** [comment]
@regel Do you have a PR for this?
