### ISSUE TITLE
Documentation of persistent volumes and distributed instances in a cluster

### ISSUE THREAD

**Issue by regel** [prologic/bitraft#40]
I'd like to contribute by writing a helm chart for Kubernetes but the documentation is missing examples:

- On persistent volumes: when the software is running in Docker, where is data persisted?
- On clustering: if multiple instances are running let say in docker-compose, what are the required parameters to spin up and join a cluster: command-line arguments, environment variables, port(s), and so on
- When bitraft cluster is running with multiple nodes, can the read and writes be sent randomly to any node inside the cluster?
- Does bitraft support data replication? If a single cluster node dies in a cluster of three nodes, will it cause data loss?

**Comment by prologic** [comment]
Wait why didn't I see this before? :O Is this new? In any case thank you! I will use this straight away 🙇‍♂️

**Comment by prologic** [comment]
Hmm really good questions 👌

First off 9f07bdc helps clarify something. I'll comment on this shortly...

**Comment by prologic** [comment]
Secondly #36 is actually a rewrite I'm trying to merge soon with @tidwall 's new [uhaha](https://github.com/tidwall/uhaha) framework.

I'm still waiting on some comments/feedback and possible improvements to uhaha from @tidwall in https://github.com/tidwall/uhaha/issues/4

**Comment by prologic** [comment]
> * On persistent volumes: when the software is running in Docker, where is data persisted?

Normally you would persist the data on local volumes. In Docker Swarm I would use named volumes here. I don't in the example [docker-stack.yml](https://github.com/prologic/bitraft/blob/master/docker-stack.yml) but I _shoudl_. This path is controlled by the `-d` flag.

> * On clustering: if multiple instances are running let say in docker-compose, what are the required parameters to spin up and join a cluster: command-line arguments, environment variables, port(s), and so on

Hopefully the example [docker-stack.yml](https://github.com/prologic/bitraft/blob/master/docker-stack.yml) helps answer this? You need to start a seed, then use that to bootstrap a cluster.

> * When bitraft cluster is running with multiple nodes, can the read and writes be sent randomly to any node inside the cluster?

The current version in master currently uses the [finn](https://github.com/tidwall/finn) framework for most of the Raft/consensus operations. If you have a read there you will see various options for Read Consistency and Write Durability.

My understanding is writes have to go to the leader _I think_. Reads _can_ be done from any node, but it depends on the level of consistency you want.

Unsure if the flags/options and code here is flexible enough, haven't used Bitraft in a while.

> * Does bitraft support data replication? If a single cluster node dies in a cluster of three nodes, will it cause data loss?

Yes, Bitraft is fully highly-available (HA) All data is written to a raft log and agreed upon by all nodes. If one node goes down out of three data remains in tact but the cluster will become unhealthy. In this case a reelection process will start (_normal raft operations apply here_). Best to run a 5-node cluste.

**Comment by regel** [comment]
HI James, thanks for clarification. I will start with Docker and continue testing HA and failure scenario to get a better feeling about cluster operations.

**Comment by prologic** [comment]
Let me know how it goes and if we can improve anything!
