### ISSUE TITLE
Service high-availability failure if one node in the cluster dies

### ISSUE THREAD

**Issue by regel** [prologic/bitraft#41]
Scenario:

1. Start a two nodes cluster
2. Second node (Follower) dies (ctrl+C to simulate the failure). Side-effect: the leader node is attempting to start a new leader election procedure
3. Then in a separate terminal I run redis-cli and connect to the leader node on port 4920
4. 'GET' query fails with error message 'ERR leader not known'
5. The leader node keeps trying to connect to the failed node permanently.

expectations:

- I would expect the leader node to fullfil the query since it still has all the data even if the cluster is not 'healthy'
- I assume the leader could forget about failed nodes. In the Kubernetes auto-scaling use-case it is common to scale up and down deployments and increase or decrease the number of pod replicas (containers) running

Logs:

### Leader

$ ./bitraft -d foo -b :4920
56619:N 16 Feb 17:18:56.935 * Enable single node
56619:N 16 Feb 17:18:56.942 * Node at :4920 [Follower] entering Follower state (Leader: "")
56619:N 16 Feb 17:18:57.990 # Heartbeat timeout from "" reached, starting election
56619:N 16 Feb 17:18:57.990 * Node at :4920 [Candidate] entering Candidate state
56619:N 16 Feb 17:18:58.003 * Election won. Tally: 1
56619:N 16 Feb 17:18:58.003 * Node at :4920 [Leader] entering Leader state
56619:N 16 Feb 17:19:20.042 * Received add peer request from :4921
56619:N 16 Feb 17:19:20.047 * Added peer :4921, starting replication
56619:N 16 Feb 17:19:20.054 # AppendEntries to :4921 rejected, sending older logs (next: 1)
56619:N 16 Feb 17:19:20.074 * Node :4921 added successfully
56619:N 16 Feb 17:21:12.769 # Failed to AppendEntries to :4921: EOF
56619:N 16 Feb 17:21:12.841 # Failed to AppendEntries to :4921: EOF
56619:N 16 Feb 17:21:12.876 # Failed to heartbeat to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:12.937 # Failed to AppendEntries to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:13.027 # Failed to AppendEntries to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:13.080 # Failed to heartbeat to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:13.155 # Failed to AppendEntries to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:13.195 # Failed to contact :4921 in 500.295555ms
56619:N 16 Feb 17:21:13.195 # Failed to contact quorum of nodes, stepping down
56619:N 16 Feb 17:21:13.195 * Node at :4920 [Follower] entering Follower state (Leader: "")
56619:N 16 Feb 17:21:14.990 # Heartbeat timeout from "" reached, starting election
56619:N 16 Feb 17:21:14.990 * Node at :4920 [Candidate] entering Candidate state
56619:N 16 Feb 17:21:14.996 # Failed to make RequestVote RPC to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:16.116 # Election timeout reached, restarting election
56619:N 16 Feb 17:21:16.116 * Node at :4920 [Candidate] entering Candidate state
56619:N 16 Feb 17:21:16.121 # Failed to make RequestVote RPC to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:17.132 # Election timeout reached, restarting election
56619:N 16 Feb 17:21:17.132 * Node at :4920 [Candidate] entering Candidate state
56619:N 16 Feb 17:21:17.137 # Failed to make RequestVote RPC to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:18.560 # Election timeout reached, restarting election
56619:N 16 Feb 17:21:18.560 * Node at :4920 [Candidate] entering Candidate state
56619:N 16 Feb 17:21:18.564 # Failed to make RequestVote RPC to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:19.971 # Election timeout reached, restarting election
56619:N 16 Feb 17:21:19.971 * Node at :4920 [Candidate] entering Candidate state
56619:N 16 Feb 17:21:19.978 # Failed to make RequestVote RPC to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:21.091 # Election timeout reached, restarting election
56619:N 16 Feb 17:21:21.091 * Node at :4920 [Candidate] entering Candidate state
56619:N 16 Feb 17:21:21.096 # Failed to make RequestVote RPC to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:22.328 # Election timeout reached, restarting election
56619:N 16 Feb 17:21:22.329 * Node at :4920 [Candidate] entering Candidate state
56619:N 16 Feb 17:21:22.334 # Failed to make RequestVote RPC to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:23.771 # Election timeout reached, restarting election
56619:N 16 Feb 17:21:23.771 * Node at :4920 [Candidate] entering Candidate state
56619:N 16 Feb 17:21:23.776 # Failed to make RequestVote RPC to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:25.139 # Election timeout reached, restarting election
56619:N 16 Feb 17:21:25.139 * Node at :4920 [Candidate] entering Candidate state
56619:N 16 Feb 17:21:25.144 # Failed to make RequestVote RPC to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:27.119 # Election timeout reached, restarting election
56619:N 16 Feb 17:21:27.119 * Node at :4920 [Candidate] entering Candidate state
56619:N 16 Feb 17:21:27.124 # Failed to make RequestVote RPC to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:28.506 # Election timeout reached, restarting election
56619:N 16 Feb 17:21:28.506 * Node at :4920 [Candidate] entering Candidate state
56619:N 16 Feb 17:21:28.511 # Failed to make RequestVote RPC to :4921: dial tcp :4921: connect: connection refused
56619:N 16 Feb 17:21:29.678 # Election timeout reached, restarting election
56619:N 16 Feb 17:21:29.678 * Node at :4920 [Candidate] entering Candidate state
56619:N 16 Feb 17:21:29.682 # Failed to make RequestVote RPC to :4921: dial tcp :4921: connect: connection refused

### Follower

$ ./bitraft -d bar -b :4921 -j localhost:4920
56623:N 16 Feb 17:19:20.042 * Node at :4921 [Follower] entering Follower state (Leader: "")
56623:N 16 Feb 17:19:20.054 # Failed to get previous log: 1 log not found (last: 0)
^C

### redis-cli

$ redis-cli -p 4920
127.0.0.1:4920> GET xx
(error) ERR leader not known

**Comment by prologic** [comment]
Hmmm I don't think this is how raft consensus works but I'll have to double check ...

**Comment by regel** [comment]
I will test the same scenario with 3 nodes and different levels of consistency and post my observations.
