### ISSUE TITLE
Follower in a healthy cluster gives 'TRY :4920' responses to redis-cli

### ISSUE THREAD

**Issue by regel** [prologic/bitraft#42]
Test scenario:

1. Start a two nodes cluster. Wait until the cluster is healthy. Leader listening on localhost port 4920. Follower listening on localhost port 4921
2. Open redis-cli on port 4921. Send a 'GET' command.
3. Observed: redis-cli receives a 'TRY :4920'

expectations:
- Since all nodes are replicas I would expect the READs to be distributed (round-robin in Kubernetes load balancer) across the nodes and respond seamlessly to the command they received

Logs:

### Leader

$ ./bitraft -d foo -b :4920

### Follower

$ ./bitraft -d bar -b :4921 -j localhost:4920
56623:N 16 Feb 17:19:20.042 * Node at :4921 [Follower] entering Follower state (Leader: "")
56623:N 16 Feb 17:19:20.054 # Failed to get previous log: 1 log not found (last: 0)
WARN[0038] unknown command: COMMAND                     

### redis-cli

$ redis-cli -p 4921
127.0.0.1:4921> GET xx
(error) TRY :4920

**Comment by prologic** [comment]
I think you have to set a lower read consistency for this to work otherwise it tries to redirect you to the leader￼

**Comment by regel** [comment]
good catch. I will try. Thanks
